### ISSUE TITLE
Panel data errror

### ISSUE THREAD

**Issue by hagen1778** [Vertamedia/clickhouse-grafana#109]
cc @simPod 

Datasource js error while trying to display graph panel.

Panel: Graph
Query: `SELECT 1`
Error: `(0 , r.flow)(...)(...).value is not a function`
StackTrace:
```
TypeError: (0 , r.flow)(...)(...).value is not a function
    at e.query (http://localhost:3000/public/plugins/vertamedia-clickhouse-datasource/module.js:11:225935)
    at t.issueQueries (http://localhost:3000/public/build/5.b2f807d050904ca29b15.js:10:94640)
    at t.issueQueries (http://localhost:3000/public/build/5.b2f807d050904ca29b15.js:10:388767)
    at http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:92198
    at http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:92295
    at c.$digest (http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:97589)
    at http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:99404
    at h (http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:33038)
    at http://localhost:3000/public/build/vendor.b2f807d050904ca29b15.js:130:34396
```

Variables querying works ok, the issue happens with graph panels. Probably connected with build rework.

**Comment by simPod** [comment]
I'm on it
